CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    level INTEGER DEFAULT 1,
    stars INTEGER DEFAULT 0, 
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER NOT NULL UNIQUE,
    soundEnabled INTEGER DEFAULT 1,
    musicEnabled INTEGER DEFAULT 1,

    FOREIGN KEY(userId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS progress (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER NOT NULL UNIQUE,
    completedLessons INTEGER DEFAULT 0,
    completedStories INTEGER DEFAULT 0,
    completedRaces INTEGER DEFAULT 0,
    completedPuzzles INTEGER DEFAULT 0,

    FOREIGN KEY(userId) REFERENCES users(id)
);