CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstName TEXT NOT NULL,
    level INTEGER DEFAULT 1,
    stars INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    soundEnabled INTEGER DEFAULT 1,
    musicEnabled INTEGER DEFAULT 1
);